# Generated by Django 4.2.1 on 2023-06-01 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 15, 26, 42, 149365)),
        ),
    ]
